version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
      