spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shortener
    username: demo
    password: secret
  jpa:
    hibernate.ddl-auto: update
    open-in-view: false
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1 h
  data:
    redis:
      host: localhost
      port: 6379
  logging:
    level:
      com.ck.shortener: DEBUG
  sql:
    init:
      mode: always
